//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package cinema.services.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "updateMIMessageResponse", namespace = "http://services.cinema/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateMIMessageResponse", namespace = "http://services.cinema/")
public class UpdateMIMessageResponse {


}
