//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package cinema.services.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "sendMailResponse", namespace = "http://services.cinema/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sendMailResponse", namespace = "http://services.cinema/")
public class SendMailResponse {

    @XmlElement(name = "return", namespace = "")
    private cinema.datas.MailData _return;

    /**
     * 
     * @return
     *     returns MailData
     */
    public cinema.datas.MailData getReturn() {
        return this._return;
    }

    /**
     * 
     * @param _return
     *     the value for the _return property
     */
    public void setReturn(cinema.datas.MailData _return) {
        this._return = _return;
    }

}
