//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package cinema.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "MailServicesService", targetNamespace = "http://services.cinema/", wsdlLocation = "WEB-INF/wsdl/MailServicesService.wsdl")
public class MailServicesService
    extends Service
{

    private final static URL MAILSERVICESSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:./WEB-INF/wsdl/MailServicesService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        MAILSERVICESSERVICE_WSDL_LOCATION = url;
    }

    public MailServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MailServicesService() {
        super(MAILSERVICESSERVICE_WSDL_LOCATION, new QName("http://services.cinema/", "MailServicesService"));
    }

    /**
     * 
     * @return
     *     returns MailServices
     */
    @WebEndpoint(name = "MailServicesPort")
    public MailServices getMailServicesPort() {
        return (MailServices)super.getPort(new QName("http://services.cinema/", "MailServicesPort"), MailServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MailServices
     */
    @WebEndpoint(name = "MailServicesPort")
    public MailServices getMailServicesPort(WebServiceFeature... features) {
        return (MailServices)super.getPort(new QName("http://services.cinema/", "MailServicesPort"), MailServices.class, features);
    }

}
