//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package cinema.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "MovInfServices", targetNamespace = "http://services.cinema/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MovInfServices {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteMIMessage", targetNamespace = "http://services.cinema/", className = "cinema.services.DeleteMIMessage")
    @ResponseWrapper(localName = "deleteMIMessageResponse", targetNamespace = "http://services.cinema/", className = "cinema.services.DeleteMIMessageResponse")
    public void deleteMIMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        MovInfData arg0);

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createMIMessage", targetNamespace = "http://services.cinema/", className = "cinema.services.CreateMIMessage")
    @ResponseWrapper(localName = "createMIMessageResponse", targetNamespace = "http://services.cinema/", className = "cinema.services.CreateMIMessageResponse")
    public void createMIMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        MovInfData arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<cinema.services.MovInfData>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMIMessageList", targetNamespace = "http://services.cinema/", className = "cinema.services.GetMIMessageList")
    @ResponseWrapper(localName = "getMIMessageListResponse", targetNamespace = "http://services.cinema/", className = "cinema.services.GetMIMessageListResponse")
    public List<MovInfData> getMIMessageList(
        @WebParam(name = "arg0", targetNamespace = "")
        MovInfData arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateMIMessage", targetNamespace = "http://services.cinema/", className = "cinema.services.UpdateMIMessage")
    @ResponseWrapper(localName = "updateMIMessageResponse", targetNamespace = "http://services.cinema/", className = "cinema.services.UpdateMIMessageResponse")
    public void updateMIMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        MovInfData arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns cinema.services.MovInfData
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveMIMessage", targetNamespace = "http://services.cinema/", className = "cinema.services.RetrieveMIMessage")
    @ResponseWrapper(localName = "retrieveMIMessageResponse", targetNamespace = "http://services.cinema/", className = "cinema.services.RetrieveMIMessageResponse")
    public MovInfData retrieveMIMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        MovInfData arg0)
        throws Exception_Exception
    ;

}
