//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package cinema.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "MovInfServicesService", targetNamespace = "http://services.cinema/", wsdlLocation = "WEB-INF/wsdl/MovInfServicesService.wsdl")
public class MovInfServicesService
    extends Service
{

    private final static URL MOVINFSERVICESSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:./WEB-INF/wsdl/MovInfServicesService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        MOVINFSERVICESSERVICE_WSDL_LOCATION = url;
    }

    public MovInfServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MovInfServicesService() {
        super(MOVINFSERVICESSERVICE_WSDL_LOCATION, new QName("http://services.cinema/", "MovInfServicesService"));
    }

    /**
     * 
     * @return
     *     returns MovInfServices
     */
    @WebEndpoint(name = "MovInfServicesPort")
    public MovInfServices getMovInfServicesPort() {
        return (MovInfServices)super.getPort(new QName("http://services.cinema/", "MovInfServicesPort"), MovInfServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MovInfServices
     */
    @WebEndpoint(name = "MovInfServicesPort")
    public MovInfServices getMovInfServicesPort(WebServiceFeature... features) {
        return (MovInfServices)super.getPort(new QName("http://services.cinema/", "MovInfServicesPort"), MovInfServices.class, features);
    }

}
