//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package cinema.services;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cinema.services package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {
	
	private final static QName _CreateMIMessageResponse_QNAME = new QName("http://services.cinema/", "createMIMessageResponse");
    private final static QName _DeleteMIMessage_QNAME = new QName("http://services.cinema/", "deleteMIMessage");
    private final static QName _RetrieveMIMessageResponse_QNAME = new QName("http://services.cinema/", "retrieveMIMessageResponse");
    private final static QName _DeleteMIMessageResponse_QNAME = new QName("http://services.cinema/", "deleteMIMessageResponse");
    private final static QName _UpdateMIMessage_QNAME = new QName("http://services.cinema/", "updateMIMessage");
    private final static QName _GetMIMessageList_QNAME = new QName("http://services.cinema/", "getMIMessageList");
    private final static QName _UpdateMIMessageResponse_QNAME = new QName("http://services.cinema/", "updateMIMessageResponse");
    private final static QName _GetMIMessageListResponse_QNAME = new QName("http://services.cinema/", "getMIMessageListResponse");
    private final static QName _CreateMIMessage_QNAME = new QName("http://services.cinema/", "createMIMessage");
    private final static QName _RetrieveMIMessage_QNAME = new QName("http://services.cinema/", "retrieveMIMessage");
    
    private final static QName _GetMessageListResponse_QNAME = new QName("http://services.cinema/", "getMessageListResponse");
    private final static QName _CreateMessage_QNAME = new QName("http://services.cinema/", "createMessage");
    private final static QName _RetrieveMessage_QNAME = new QName("http://services.cinema/", "retrieveMessage");
    private final static QName _CreateMessageResponse_QNAME = new QName("http://services.cinema/", "createMessageResponse");
    private final static QName _DeleteMessage_QNAME = new QName("http://services.cinema/", "deleteMessage");
    private final static QName _RetrieveMessageResponse_QNAME = new QName("http://services.cinema/", "retrieveMessageResponse");
    private final static QName _DeleteMessageResponse_QNAME = new QName("http://services.cinema/", "deleteMessageResponse");
    private final static QName _UpdateMessage_QNAME = new QName("http://services.cinema/", "updateMessage");
    private final static QName _GetMessageList_QNAME = new QName("http://services.cinema/", "getMessageList");
    private final static QName _UpdateMessageResponse_QNAME = new QName("http://services.cinema/", "updateMessageResponse");
    
    private final static QName _SendMailResponse_QNAME = new QName("http://services.cinema/", "sendMailResponse");
    private final static QName _CreateMail_QNAME = new QName("http://services.cinema/", "createMail");
    private final static QName _CreateMailResponse_QNAME = new QName("http://services.cinema/", "createMailResponse");
    private final static QName _GetMailList_QNAME = new QName("http://services.cinema/", "getMailList");
    private final static QName _GetMailListResponse_QNAME = new QName("http://services.cinema/", "getMailListResponse");
    private final static QName _Exception_QNAME = new QName("http://services.cinema/", "Exception");
    private final static QName _SendMail_QNAME = new QName("http://services.cinema/", "sendMail");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cinema.services
     * 
     */
    public ObjectFactory() {
    }
    
    /**
     * Create an instance of {@link UpdateMIMessage }
     * 
     */
    public UpdateMIMessage createUpdateMIMessage() {
        return new UpdateMIMessage();
    }

    /**
     * Create an instance of {@link DeleteMessageResponse }
     * 
     */
    public DeleteMessageResponse createDeleteMessageResponse() {
        return new DeleteMessageResponse();
    }

    /**
     * Create an instance of {@link TicketData }
     * 
     */
    public TicketData createTicketData() {
        return new TicketData();
    }

    /**
     * Create an instance of {@link GetMessageList }
     * 
     */
    public GetMessageList createGetMessageList() {
        return new GetMessageList();
    }

    /**
     * Create an instance of {@link UpdateMessage }
     * 
     */
    public UpdateMessage createUpdateMessage() {
        return new UpdateMessage();
    }

    /**
     * Create an instance of {@link CreateMessageResponse }
     * 
     */
    public CreateMessageResponse createCreateMessageResponse() {
        return new CreateMessageResponse();
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link DeleteMessage }
     * 
     */
    public DeleteMessage createDeleteMessage() {
        return new DeleteMessage();
    }

    /**
     * Create an instance of {@link GetMessageListResponse }
     * 
     */
    public GetMessageListResponse createGetMessageListResponse() {
        return new GetMessageListResponse();
    }

    /**
     * Create an instance of {@link UpdateMessageResponse }
     * 
     */
    public UpdateMessageResponse createUpdateMessageResponse() {
        return new UpdateMessageResponse();
    }

    /**
     * Create an instance of {@link RetrieveMessageResponse }
     * 
     */
    public RetrieveMessageResponse createRetrieveMessageResponse() {
        return new RetrieveMessageResponse();
    }

    /**
     * Create an instance of {@link RetrieveMessage }
     * 
     */
    public RetrieveMessage createRetrieveMessage() {
        return new RetrieveMessage();
    }

    /**
     * Create an instance of {@link CreateMessage }
     * 
     */
    public CreateMessage createCreateMessage() {
        return new CreateMessage();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMessageListResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "getMessageListResponse")
    public JAXBElement<GetMessageListResponse> createGetMessageListResponse(GetMessageListResponse value) {
        return new JAXBElement<GetMessageListResponse>(_GetMessageListResponse_QNAME, GetMessageListResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "createMessage")
    public JAXBElement<CreateMessage> createCreateMessage(CreateMessage value) {
        return new JAXBElement<CreateMessage>(_CreateMessage_QNAME, CreateMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetrieveMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "retrieveMessage")
    public JAXBElement<RetrieveMessage> createRetrieveMessage(RetrieveMessage value) {
        return new JAXBElement<RetrieveMessage>(_RetrieveMessage_QNAME, RetrieveMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateMessageResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "createMessageResponse")
    public JAXBElement<CreateMessageResponse> createCreateMessageResponse(CreateMessageResponse value) {
        return new JAXBElement<CreateMessageResponse>(_CreateMessageResponse_QNAME, CreateMessageResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "deleteMessage")
    public JAXBElement<DeleteMessage> createDeleteMessage(DeleteMessage value) {
        return new JAXBElement<DeleteMessage>(_DeleteMessage_QNAME, DeleteMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetrieveMessageResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "retrieveMessageResponse")
    public JAXBElement<RetrieveMessageResponse> createRetrieveMessageResponse(RetrieveMessageResponse value) {
        return new JAXBElement<RetrieveMessageResponse>(_RetrieveMessageResponse_QNAME, RetrieveMessageResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteMessageResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "deleteMessageResponse")
    public JAXBElement<DeleteMessageResponse> createDeleteMessageResponse(DeleteMessageResponse value) {
        return new JAXBElement<DeleteMessageResponse>(_DeleteMessageResponse_QNAME, DeleteMessageResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "updateMessage")
    public JAXBElement<UpdateMessage> createUpdateMessage(UpdateMessage value) {
        return new JAXBElement<UpdateMessage>(_UpdateMessage_QNAME, UpdateMessage.class, null, value);
    }

 

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMessageList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "getMessageList")
    public JAXBElement<GetMessageList> createGetMessageList(GetMessageList value) {
        return new JAXBElement<GetMessageList>(_GetMessageList_QNAME, GetMessageList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateMessageResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "updateMessageResponse")
    public JAXBElement<UpdateMessageResponse> createUpdateMessageResponse(UpdateMessageResponse value) {
        return new JAXBElement<UpdateMessageResponse>(_UpdateMessageResponse_QNAME, UpdateMessageResponse.class, null, value);
    }
    
    
    /**
     * Create an instance of {@link CreateMIMessageResponse }
     * 
     */
    public CreateMIMessageResponse createCreateMIMessageResponse() {
        return new CreateMIMessageResponse();
    }

    /**
     * Create an instance of {@link RetrieveMIMessageResponse }
     * 
     */
    public RetrieveMIMessageResponse createRetrieveMIMessageResponse() {
        return new RetrieveMIMessageResponse();
    }

    /**
     * Create an instance of {@link DeleteMIMessage }
     * 
     */
    public DeleteMIMessage createDeleteMIMessage() {
        return new DeleteMIMessage();
    }

    /**
     * Create an instance of {@link CreateMIMessage }
     * 
     */
    public CreateMIMessage createCreateMIMessage() {
        return new CreateMIMessage();
    }

    /**
     * Create an instance of {@link RetrieveMIMessage }
     * 
     */
    public RetrieveMIMessage createRetrieveMIMessage() {
        return new RetrieveMIMessage();
    }

    /**
     * Create an instance of {@link DeleteMIMessageResponse }
     * 
     */
    public DeleteMIMessageResponse createDeleteMIMessageResponse() {
        return new DeleteMIMessageResponse();
    }


    /**
     * Create an instance of {@link GetMIMessageList }
     * 
     */
    public GetMIMessageList createGetMIMessageList() {
        return new GetMIMessageList();
    }

    /**
     * Create an instance of {@link MovInfData }
     * 
     */
    public MovInfData createMovInfData() {
        return new MovInfData();
    }

    /**
     * Create an instance of {@link GetMIMessageListResponse }
     * 
     */
    public GetMIMessageListResponse createGetMIMessageListResponse() {
        return new GetMIMessageListResponse();
    }

    /**
     * Create an instance of {@link UpdateMIMessageResponse }
     * 
     */
    public UpdateMIMessageResponse createUpdateMIMessageResponse() {
        return new UpdateMIMessageResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateMIMessageResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "createMIMessageResponse")
    public JAXBElement<CreateMIMessageResponse> createCreateMIMessageResponse(CreateMIMessageResponse value) {
        return new JAXBElement<CreateMIMessageResponse>(_CreateMIMessageResponse_QNAME, CreateMIMessageResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteMIMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "deleteMIMessage")
    public JAXBElement<DeleteMIMessage> createDeleteMIMessage(DeleteMIMessage value) {
        return new JAXBElement<DeleteMIMessage>(_DeleteMIMessage_QNAME, DeleteMIMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetrieveMIMessageResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "retrieveMIMessageResponse")
    public JAXBElement<RetrieveMIMessageResponse> createRetrieveMIMessageResponse(RetrieveMIMessageResponse value) {
        return new JAXBElement<RetrieveMIMessageResponse>(_RetrieveMIMessageResponse_QNAME, RetrieveMIMessageResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteMIMessageResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "deleteMIMessageResponse")
    public JAXBElement<DeleteMIMessageResponse> createDeleteMIMessageResponse(DeleteMIMessageResponse value) {
        return new JAXBElement<DeleteMIMessageResponse>(_DeleteMIMessageResponse_QNAME, DeleteMIMessageResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateMIMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "updateMIMessage")
    public JAXBElement<UpdateMIMessage> createUpdateMIMessage(UpdateMIMessage value) {
        return new JAXBElement<UpdateMIMessage>(_UpdateMIMessage_QNAME, UpdateMIMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMIMessageList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "getMIMessageList")
    public JAXBElement<GetMIMessageList> createGetMIMessageList(GetMIMessageList value) {
        return new JAXBElement<GetMIMessageList>(_GetMIMessageList_QNAME, GetMIMessageList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateMIMessageResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "updateMIMessageResponse")
    public JAXBElement<UpdateMIMessageResponse> createUpdateMIMessageResponse(UpdateMIMessageResponse value) {
        return new JAXBElement<UpdateMIMessageResponse>(_UpdateMIMessageResponse_QNAME, UpdateMIMessageResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMIMessageListResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "getMIMessageListResponse")
    public JAXBElement<GetMIMessageListResponse> createGetMIMessageListResponse(GetMIMessageListResponse value) {
        return new JAXBElement<GetMIMessageListResponse>(_GetMIMessageListResponse_QNAME, GetMIMessageListResponse.class, null, value);
    }

    

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateMIMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "createMIMessage")
    public JAXBElement<CreateMIMessage> createCreateMIMessage(CreateMIMessage value) {
        return new JAXBElement<CreateMIMessage>(_CreateMIMessage_QNAME, CreateMIMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetrieveMIMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "retrieveMIMessage")
    public JAXBElement<RetrieveMIMessage> createRetrieveMIMessage(RetrieveMIMessage value) {
        return new JAXBElement<RetrieveMIMessage>(_RetrieveMIMessage_QNAME, RetrieveMIMessage.class, null, value);
    }


    /**
     * Create an instance of {@link SendMail }
     * 
     */
    public SendMail createSendMail() {
        return new SendMail();
    }

    /**
     * Create an instance of {@link SendMailResponse }
     * 
     */
    public SendMailResponse createSendMailResponse() {
        return new SendMailResponse();
    }

    /**
     * Create an instance of {@link CreateMail }
     * 
     */
    public CreateMail createCreateMail() {
        return new CreateMail();
    }

    
    /**
     * Create an instance of {@link GetMailListResponse }
     * 
     */
    public GetMailListResponse createGetMailListResponse() {
        return new GetMailListResponse();
    }

    /**
     * Create an instance of {@link MailData }
     * 
     */
    public MailData createMailData() {
        return new MailData();
    }

    /**
     * Create an instance of {@link GetMailList }
     * 
     */
    public GetMailList createGetMailList() {
        return new GetMailList();
    }

    /**
     * Create an instance of {@link CreateMailResponse }
     * 
     */
    public CreateMailResponse createCreateMailResponse() {
        return new CreateMailResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendMailResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "sendMailResponse")
    public JAXBElement<SendMailResponse> createSendMailResponse(SendMailResponse value) {
        return new JAXBElement<SendMailResponse>(_SendMailResponse_QNAME, SendMailResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateMail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "createMail")
    public JAXBElement<CreateMail> createCreateMail(CreateMail value) {
        return new JAXBElement<CreateMail>(_CreateMail_QNAME, CreateMail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateMailResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "createMailResponse")
    public JAXBElement<CreateMailResponse> createCreateMailResponse(CreateMailResponse value) {
        return new JAXBElement<CreateMailResponse>(_CreateMailResponse_QNAME, CreateMailResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMailList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "getMailList")
    public JAXBElement<GetMailList> createGetMailList(GetMailList value) {
        return new JAXBElement<GetMailList>(_GetMailList_QNAME, GetMailList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMailListResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "getMailListResponse")
    public JAXBElement<GetMailListResponse> createGetMailListResponse(GetMailListResponse value) {
        return new JAXBElement<GetMailListResponse>(_GetMailListResponse_QNAME, GetMailListResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Exception }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "Exception")
    public JAXBElement<Exception> createException(Exception value) {
        return new JAXBElement<Exception>(_Exception_QNAME, Exception.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendMail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.cinema/", name = "sendMail")
    public JAXBElement<SendMail> createSendMail(SendMail value) {
        return new JAXBElement<SendMail>(_SendMail_QNAME, SendMail.class, null, value);
    }

}
