//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package cinema.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "TicketServicesService", targetNamespace = "http://services.cinema/", wsdlLocation = "WEB-INF/wsdl/TicketServicesService.wsdl")
public class TicketServicesService
    extends Service
{

    private final static URL TICKETSERVICESSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:./WEB-INF/wsdl/TicketServicesService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        TICKETSERVICESSERVICE_WSDL_LOCATION = url;
    }

    public TicketServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TicketServicesService() {
        super(TICKETSERVICESSERVICE_WSDL_LOCATION, new QName("http://services.cinema/", "TicketServicesService"));
    }

    /**
     * 
     * @return
     *     returns TicketServices
     */
    @WebEndpoint(name = "TicketServicesPort")
    public TicketServices getTicketServicesPort() {
        return (TicketServices)super.getPort(new QName("http://services.cinema/", "TicketServicesPort"), TicketServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TicketServices
     */
    @WebEndpoint(name = "TicketServicesPort")
    public TicketServices getTicketServicesPort(WebServiceFeature... features) {
        return (TicketServices)super.getPort(new QName("http://services.cinema/", "TicketServicesPort"), TicketServices.class, features);
    }

}
